### PR TITLE
Support for building behind a proxy

### PR DESCRIPTION
**Pull request by j616**
Hello. Thanks for your work on this container. 

I've found that it doesn't build behind a proxy due to the old version of gpg in stretch and a mixing argument.

The changes in this PR fix this though require changing the base image. It also seems like you have another mechanism for generating images from a template. I'm not sure if you are making use of that or just manually editing the Dockerfile?

### CODE REVIEW

**Comment by j616** [comment]
Error in the CI is due to the `$http_proxy` env var not being set. I'll fix that.

**Comment by cyny39** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
felixsevero, @paulogrell, @rfperuch, @elccastro, @debemdeboas, @karlos-oliveira, @MatheusPortal, @btg-unofficial-merchant-sdk, @ogecece, @eletroswing, @crzypatchwork, @mtaarao, @AndersonVazquez, @Oguima, @StudioDnerg, @rodrigopuls, @jalmoreno, @wzomer, @Jeankininho, @turtle071

**Comment by yogeshkushwahait** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
ZaqueuCavalcante, @debemdeboas, @matl4zaro, @diogobest, @dionisioedu, @rafaeljustinox, @guidani, @Rafael-Totino, @appfromape, @th3rius, @arthurmichel, @rilder-almeida, @alvesa, @PcFerreira, @ermogenes, @rockletz, @LeonardoWiest, @BrunoDPO, @yuri-potatoq, @randrade86

**Comment by j616** [comment]
Closing due to lack of progress, and effort becoming available on our end to revive this PR seeming unlikely

**Pull request closed without merging**
